# Generated by Django 4.2.5 on 2023-10-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_options_remove_productmodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
